// Generated by CoffeeScript 1.3.3
(function() {
  var GameBoard;

  GameBoard = (function() {

    GameBoard.prototype.cellSize = 10;

    GameBoard.prototype.numRows = 50;

    GameBoard.prototype.numColumns = 50;

    GameBoard.prototype.cellStates = null;

    GameBoard.prototype.canvas = null;

    GameBoard.prototype.ctx = null;

    function GameBoard() {
      this.buildCanvas();
      this.createGrid();
      this.drawGrid();
    }

    GameBoard.prototype.buildCanvas = function() {
      this.canvas = document.createElement('canvas');
      $(this.canvas).addClass('gameboard');
      document.body.appendChild(this.canvas);
      this.canvas.height = this.cellSize * this.numRows;
      this.canvas.width = this.cellSize * this.numColumns;
      return this.ctx = this.canvas.getContext('2d');
    };

    GameBoard.prototype.createGrid = function() {
      var column, row, _i, _ref, _results;
      this.cellStates = [];
      _results = [];
      for (row = _i = 0, _ref = this.numRows; 0 <= _ref ? _i < _ref : _i > _ref; row = 0 <= _ref ? ++_i : --_i) {
        this.cellStates[row] = [];
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (column = _j = 0, _ref1 = this.numColumns; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; column = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(this.cellStates[row][column] = 0);
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    GameBoard.prototype.drawGrid = function() {
      var col, row, _i, _ref, _results;
      _results = [];
      for (row = _i = 0, _ref = this.numRows; 0 <= _ref ? _i < _ref : _i > _ref; row = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (col = _j = 0, _ref1 = this.numColumns; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(this.drawCell(row, col));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    GameBoard.prototype.drawCell = function(row, col) {
      var fillStyle, x, y;
      x = col * this.cellSize;
      y = row * this.cellSize;
      this.ctx.strokeStyle = 'rgba(100, 100, 100, 1.0)';
      this.ctx.strokeRect(x, y, this.cellSize, this.cellSize);
      if (this.cellStates[row][col] === 0) {
        fillStyle = 'rgb(50, 50, 50)';
      } else {
        fillStyle = 'rgb(200, 100, 0)';
      }
      this.ctx.fillStyle = fillStyle;
      return this.ctx.fillRect(x, y, this.cellSize, this.cellSize);
    };

    GameBoard.prototype.setCellState = function(row, col, val) {
      this.cellStates[row][col] = val;
      return this.drawCell(row, col);
    };

    GameBoard.prototype.getCellState = function(row, col) {
      return this.cellStates[row][col];
    };

    return GameBoard;

  })();

  window.GameBoard = GameBoard;

}).call(this);
